name: Build and Upload Android Build

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: '-DGITHUB_BUILD'
      save-artifact:
        type: boolean
        description: Save the build artifact to Github Actions
        default: true

jobs:

  build-game-on-linux:
    runs-on: ubuntu-latest  # Usamos la máquina virtual limpia de GitHub
    defaults:
      run:
        shell: bash
    env:
      BUILD_DEFINES: ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Trae los submódulos de FNF

      - name: Setup Lix/Haxe Environment
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4 # Instalación nativa y limpia de la versión exacta

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Config haxelib
        run: |
          haxelib --never newrepo
          echo "HAXEPATH=$(haxelib config)" >> "$GITHUB_ENV"

      - name: Install HMM and dependencies
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install -q
          # Compilar herramientas internas de hxcpp para C++
          cd .haxelib/hxcpp/git/tools/hxcpp && haxe compile.hxml

      - name: Build game (Android)
        run: |
          haxelib run lime build android -v -release $BUILD_DEFINES
        timeout-minutes: 60

      - name: Save APK artifact to Github Actions
        if: ${{ github.event.inputs.save-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build-android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
