name: Build and Upload Android Build

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: '-DGITHUB_BUILD'
      save-artifact:
        type: boolean
        description: Save the build artifact to Github Actions
        default: true # Cambiado a true por defecto para que descargues el APK directo desde GitHub

jobs:

  gather-tags:
    runs-on: ubuntu-latest # Cambiado a servidor público de Linux
    outputs:
      primary: ${{ steps.build-tags.outputs.primary }}
    steps:
      - name: Gather build tags
        uses: actions/github-script@v7
        id: build-tags
        with:
          script: |
            const ref_path = context.ref.split("/").slice(2)
            const ref_tag = ref_path.join("-")
            core.setOutput("primary", ref_tag)

  build-game-in-container:
    needs: [gather-tags]
    runs-on: ubuntu-latest # Cambiado a servidor público de Linux
    # Usamos una imagen de Docker pública de Haxe/Ubuntu estable para evitar el registro privado de FNF
    container: haxe:4.3.4-ubuntu
    defaults:
      run:
        shell: bash
    env:
      BUILD_DEFINES: ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Trae todos los submódulos necesarios del juego

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Config haxelib
        run: |
          haxelib --never newrepo
          echo "HAXEPATH=$(haxelib config)" >> "$GITHUB_ENV"

      - name: Install HMM and dependencies
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install -q
          # Configurar hxcpp para compilación en C++
          cd .haxelib/hxcpp/git/tools/hxcpp && haxe compile.hxml

      - name: Build game (Android)
        run: |
          haxelib run lime build android -v -release $BUILD_DEFINES
        timeout-minutes: 60

      - name: Save APK artifact to Github Actions
        if: ${{ github.event.inputs.save-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build-android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
